name: Deploy Heroku Workflow

on:
  push:
    branches: [master]

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3.0.2
      - uses: ArtiomTr/jest-coverage-report-action@v2
